nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: http://github.com/fjkfwz
  Search: /Search/

projects_url: http://github.com/fjkfwz


customize:
    gravatar:
        email: fjkfwz@gmail.com
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: http://github.com/fjkfwz
        twitter: https://twitter.com/AndyMckees
        facebook: https://www.facebook.com/mckee.andy1
        linkedin: https://www.linkedin.com/in/andy-mckees-6605204b/
    show_all_posts: false
    post_count: 20
    highlight: rainbow

# RSS
rss: atom.xml

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
